ecss/config/routes.rb
Rails.application.routes.draw do
  resources :hospitals do
    resources :patients do
      resources :families
    end
  end
end

ecss/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ecss/app/models/family.rb
class Family < ApplicationRecord
  belongs_to :patient

  validates :name, presence: true
  validates :tel, presence: true
  validates :mail, presence: true
  validates :postcode, presence: true
  validates :address, presence: true

end

ecss/app/models/hospital.rb
class Hospital < ApplicationRecord
  has_many :patients

  validates :name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :tel, presence: true
  validates :mail, presence: true
  validates :postcode, presence: true
  validates :address, presence: true

end

ecss/app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :hospital
  has_one :family

  validates :name, presence: true
  validates :tel, presence: true
  validates :mail, presence: true
  validates :postcode, presence: true
  validates :address, presence: true
  validates :disease, presence: true

  def age
    date_format = "%Y%m%d"
    if birthday.present?
      (Date.today.strftime(date_format).to_i - birthday.strftime(date_format).to_i) / 10000
    else
      nil
    end
  end

end

ecss/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

ecss/app/controllers/families_controller.rb
class FamiliesController < ApplicationController

  def show
    @family = Family.find(params[:id])
    @patient = @family.patient
    @hospital = @patient.hospital
  end

  def new
    @hospital = Hospital.find(params[:hospital_id])
    @patient = Patient.find(params[:patient_id])
    @family = Family.new
  end

  def create
    @family = Family.new(family_params)
    if @family.save
      redirect_to controller: :families, action: :show, id: @family.id,  notice: "登録しました"
    else
      @family = Family.find(params[:id])
      @patient = @family.patient
      @hospital = @patient.hospital
      render action: :new
    end
  end

  def edit
    @family = Family.find(params[:id])
    @patient = @family.patient
    @hospital = @patient.hospital
  end

  def update
    @family = Family.find(params[:id])
    if @family.update(family_params)
      redirect_to controller: :families, action: :show, id: @family.id,  notice: "編集しました"
    else
      @patient = @family.patient
      @hospital = @patient.hospital
      render action: :edit
    end
  end


  private
  def family_params
    params.require(:family).permit(:name, :postcode, :address, :tel, :mail).merge(patient_id: params[:patient_id])
  end
end

ecss/app/controllers/hospitals_controller.rb
class HospitalsController < ApplicationController
  def index
  end

  def show
    @hospital = Hospital.find(params[:id])
  end

  def new
    @hospital = Hospital.new
  end

  def create
    @hospital = Hospital.new(hospital_params)
    if @hospital.save
      redirect_to controller: :hospitals, action: :show, id: @hospital.id,  notice: "登録しました"
    else
      @hospital = Hosiptal.find(params[:hospital_id])
      render action: :new
    end
  end

  def edit
    @hospital = Hospital.find(params[:id])
  end

  def update
    @hospital = Hospital.find(params[:id])
    if @hospital.update(hospital_params)
      redirect_to controller: :hospitals, action: :show, id: @hospital.id,  notice: "編集しました"
    else
      @hospital = Hospital.find(params[:hospital_id])
      render action: :edit
    end
  end

  private
  def hospital_params
    params.require(:hospital).permit(:name, :username, :tel, :mail, :postcode, :address)
  end
end

ecss/app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @hospital = Hospital.find(params[:hospital_id])
    @patients = @hospital.patients
  end

  def show
    @patient = Patient.find(params[:id])
    @hospital = @patient.hospital
  end

  def new
    @hospital = Hospital.find(params[:hospital_id])
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to controller: :patients, action: :show, id: @patient.id,  notice: "登録しました"
    else
      @patient = Patient.find(params[:id])
      @hospital = @patient.hospital
      render action: :new
    end
  end

  def edit
    @patient = Patient.find(params[:id])
    @hospital = @patient.hospital
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient.update(patient_params)
      redirect_to controller: :patients, action: :show, id: @patient.id,  notice: "編集しました"
    else
      @patient = Patient.find(params[:id])
      @hospital = @patient.hospital
      render action: :edit
    end
  end

  private
  def patient_params
    params.require(:patient).permit(:name, :birthday, :postcode, :address, :tel, :mail, :disease, :dash_id).merge(hospital_id: params[:hospital_id])
  end
end

ecss/app/helpers/application_helper.rb
module ApplicationHelper
end

ecss/app/helpers/families_helper.rb
module FamiliesHelper
end

ecss/app/helpers/hospitals_helper.rb
module HospitalsHelper
end

ecss/app/helpers/patients_helper.rb
module PatientsHelper
end

ecss/app/views/common/_header.html.erb
<nav class="navbar navbar-default header">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand header__logo" href="#">ECSS</a>
    </div>

  </div><!-- /.container-fluid -->
</nav>

ecss/app/views/families/edit.html.erb
<%= form_for [@hospital, @patient, @family] do |f| %>
  <% if @family.errors.any? %>
    <div class="alert alert-danger text-center" role="alert">
      <h4><%= @family.errors.count %>件の未記入のところがあります。</h4>
      <% @family.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>
  <div class="row">
    <div class="form-horizontal">
      <div class="form-group">
        <%= f.label :名前, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :name, placeholder: "名前", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :電話番号, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :tel, placeholder: "電話番号", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :メールアドレス, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.email_field :mail, placeholder: "メールアドレス", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :郵便番号, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :postcode, placeholder: "郵便番号", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :住所, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :address, placeholder: "住所", class: "form-control" %>
        </div>
      </div>

      <div class="form-group update-button">
          <div class="col-sm-5 col-sm-offset-4">
            <%= f.submit "更新する", class: "btn btn-color btn-group-justified" %>
          </div>
        </div>
    </div>
  </div>
<% end %>

ecss/app/views/families/new.html.erb
<%= form_for [@hospital, @patient, @family] do |f| %>
  <% if @family.errors.any? %>
    <div class="alert alert-danger text-center" role="alert">
      <h4><%= @family.errors.count %>件の未記入のところがあります。</h4>
      <% @family.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>
  <div class="row">
    <div class="form-horizontal">
      <div class="form-group">
        <%= f.label :名前, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :name, placeholder: "名前", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :電話番号, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :tel, placeholder: "電話番号", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :メールアドレス, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.email_field :mail, placeholder: "メールアドレス", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :郵便番号, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :postcode, placeholder: "郵便番号", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :住所, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :address, placeholder: "住所", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
          <div class="col-sm-5 col-sm-offset-4">
            <%= f.submit "登録する", class: "btn btn-danger btn-group-justified" %>
          </div>
        </div>
    </div>
  </div>
<% end %>

ecss/app/views/families/show.html.erb
<div class="right-content__main">
  <div class="row">
    <div class="col-md-9 col-md-offset-1">
  <table class="table table-striped table-bordered">
    <p class="title-bar">
      <span>家族情報</span>
    </p>
    <tbody>
      <tr>
        <div class="row">
        <th class="col-md-2">患者</th>
        <td class="col-md-6"><%= @patient.name %></td>
        </div>
      </tr>
      <tr>
        <th>家族の名前</th>
        <td><%= @family.name %></td>
      </tr>
      <tr>
        <th>電話番号</th>
        <td><%= @family.tel %></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @family.mail %></td>
      </tr>
      <tr>
        <th>所在地</th>
        <td>
          〒<%= @family.postcode %><br>
          <%= @family.address %>
        </td>
      </tr>
    </tbody>
  </table>
  <%= link_to hospital_patients_path(@hospital), class: "btn btn-default" do %>
    <i class="fa fa-chevron-left fa-fw" aria-hidden="true"></i>一覧に戻る
  <% end %>
  <%= link_to "患者情報", hospital_patient_path(@hospital, @patient), class: "btn btn-default" %>
  <%= link_to "編集", edit_hospital_patient_family_path(@hospital, @patient, @family), class: "btn btn-default" %>
</div>

ecss/app/views/hospitals/edit.html.erb
<%= form_for @hospital do |f| %>
  <% if @hospital.errors.any? %>
    <div class="alert alert-danger text-center" role="alert">
      <h4><%= @hospital.errors.count %>件の未記入のところがあります。</h4>
      <% @hospital.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>
  <div class="row">
    <div class="form-horizontal">
      <div class="form-group">
        <%= f.label :名前, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :name, placeholder: "病院名", class: "form-control" %>
        </div>
      </div><!-- form-group -->

      <div class="form-group">
        <%= f.label :ログインID, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :username, placeholder: "ログインID（半角英数字）", class: "form-control" %>
        </div>
        <div class="col-md-5">
        </div>
      </div><!-- form-group -->

      <div class="form-group">
        <%= f.label :電話番号, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :name, placeholder: "電話番号", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :メールアドレス, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.email_field :mail, placeholder: "メールアドレス", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :郵便番号, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :postcode, placeholder: "郵便番号", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :住所, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :address, placeholder: "住所", class: "form-control" %>
        </div>
      </div>

      <div class="form-group update-button">
        <div class="col-sm-5 col-sm-offset-4">
          <%= f.submit "更新する", class: "btn btn-danger btn-group-justified" %>
        </div>
      </div><!-- form-group update-button-->
    </div><!-- form-horizontal -->
  </div><!-- row -->
<% end %>

ecss/app/views/hospitals/new.html.erb
<%= form_for @hospital do |f| %>
  <% if @hospital.errors.any? %>
    <div class="alert alert-danger text-center" role="alert">
      <h4><%= @hospital.errors.count %>件の未記入のところがあります。</h4>
      <% @hospital.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>
  <div class="row">
    <div class="form-horizontal">
      <div class="form-group">
        <%= f.label :名前, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :name, placeholder: "病院名", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :ログインID, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :username, placeholder: "ログインID（半角英数字）", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :電話番号, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :tel, placeholder: "電話番号", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :メールアドレス, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :mail, placeholder: "メールアドレス", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :郵便番号, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :postcode, placeholder: "郵便番号", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :住所, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :address, placeholder: "住所", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-5 col-sm-offset-4 update-button">
          <%= f.submit "登録する", class: "btn btn-danger btn-group-justified" %>
        </div>
      </div><!-- form-group update-button -->
    </div><!-- form-horizontal -->
  </div><!-- row -->
<% end %>

ecss/app/views/hospitals/show.html.erb
<div class="right-content__main">
  <div class="row">
    <div class="col-md-9 col-md-offset-1">
      <table class="table table-striped table-bordered">
        <p class="title-bar">
          <span>病院情報</span>
        </p>
        <tbody>
          <tr>
            <div class="row">
              <th class="col-md-2">名称</th>
              <td class="col-md-6"><%= @hospital.name %></td>
            </div>
          </tr>
          <tr>
            <div class="row">
              <th class="col-md-2">ログインID</th>
              <td class="col-md-6"><%= @hospital.username %></td>
            </div>
          </tr>
          <tr>
            <div class="row">
              <th class="col-md-2">電話番号</th>
              <td class="col-md-6"><%= @hospital.tel %></td>
            </div>
          </tr>
          <tr>
            <div class="row">
              <th class="col-md-2">メールアドレス</th>
              <td class="col-md-6"><%= @hospital.mail %></td>
            </div>
          </tr>
          <tr>
            <div class="row">
              <th class="col-md-2">所在地</th>
              <td class="col-md-6">
                〒<%= @hospital.postcode %><br>
                <%= @hospital.address %>
              </td>
          </tr>
        </tbody>
      </table>
        <%= link_to hospital_patients_path(@hospital), class: "btn btn-color" do %>
          <i class="fa fa-users fa-fw" aria-hidden="true"></i>患者一覧
        <% end %>
        <%= link_to "患者登録", new_hospital_patient_path(@hospital), class: "btn btn-default" %>
        <%= link_to "編集", edit_hospital_path(@hospital), class: "btn btn-default" %>
    </div><!-- col-md-9 -->
  </div><!-- row -->
</div>

ecss/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='ja'>
  <head>
    <meta charset = 'utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1'>
    <meta name='viewport' content='width=device-width, initial-scale=1.0'>
    <title>ECSS</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

  <%= render partial: "common/header" %>

  <div class="container">
    <%= yield %>
  </div>

  </body>
</html>

ecss/app/views/patients/edit.html.erb
<%= form_for [@hospital, @patient] do |f| %>
  <% if @patient.errors.any? %>
    <div class="alert alert-danger text-center" role="alert">
      <h4><%= @patient.errors.count %>件の未記入のところがあります。</h4>
      <% @patient.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>
  <div class="row">
    <div class="form-horizontal">
      <div class="form-group">
        <%= f.label :名前, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :name, placeholder: "名前", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :生年月日, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.date_select :birthday, {default_year: Time.now.year - 20, use_month_numbers: :true, start_year: Time.now.year - 70, end_year:  Time.now.year} %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :電話番号, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :tel, placeholder: "電話番号", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :メールアドレス, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.email_field :mail, placeholder: "メールアドレス", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :郵便番号, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :postcode, placeholder: "郵便番号", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :住所, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :address, placeholder: "住所", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :病気名, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :disease, placeholder: "病気名", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :ダッシュID, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :dash_id, placeholder: "ダッシュID", class: "form-control" %>
        </div>
      </div>

      <div class="form-group update-button">
        <div class="col-sm-5 col-sm-offset-4">
          <%= f.submit "更新する", class: "btn btn-danger btn-group-justified" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

ecss/app/views/patients/index.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>ID</th>
      <th>患者名</th>
      <th>病名</th>
      <th>年齢</th>
      <th>住所</th>
      <th>電話番号</th>
      <th>カルテ</th>
    </tr>
  </thead>
  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= link_to patient.id, hospital_patient_path(@hospital, patient) %></td>
        <td><%= patient.name %></td>
        <td><%= patient.disease %></td>
        <td class="text-right"><%= patient.age %>歳</td>
        <td><%= patient.address %></td>
        <td><%= patient.tel %></td>
        <td><button type="button" class="btn btn-success btn-xs">表示</button></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "患者登録", new_hospital_patient_path(@hospital), class: "btn btn-default" %>

ecss/app/views/patients/new.html.erb
<%= form_for [@hospital, @patient] do |f| %>
  <% if @patient.errors.any? %>
    <div class="alert alert-danger text-center" role="alert">
      <h4><%= @patient.errors.count %>件の未記入のところがあります。</h4>
      <% @patient.errors.full_messages.each do |message| %>
        <p><%= message %></p>
      <% end %>
    </div>
  <% end %>
  <div class="row">
    <div class="form-horizontal">
      <div class="form-group">
        <%= f.label :名前, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :name, placeholder: "名前", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :生年月日, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.date_select :birthday, {default_year: Time.now.year - 20, use_month_numbers: :true, start_year: Time.now.year - 70, end_year:  Time.now.year} %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :電話番号, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :tel, placeholder: "電話番号", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :メールアドレス, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.email_field :mail, placeholder: "メールアドレス", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :郵便番号, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :postcode, placeholder: "郵便番号", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :住所, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :address, placeholder: "住所", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :病気名, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :disease, placeholder: "病気名", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :ダッシュID, class: "col-md-4 control-label" %>
        <div class="col-md-5">
          <%= f.text_field :dash_id, placeholder: "ダッシュID", class: "form-control" %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-5 col-sm-offset-4">
          <%= f.submit "登録する", class: "btn btn-danger btn-group-justified" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

ecss/app/views/patients/show.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <table class="table table-striped table-bordered">
      <p class="title-bar">
        <span>患者情報</span>
      </p>
      <tbody>
        <tr>
          <div class="row">
            <th class="col-md-2">ID</th>
            <td class="col-md-6"><%= @patient.id %></td>
          </div>
        </tr>
        <tr>
          <th>名称</th>
          <td><%= @patient.name %></td>
        </tr>
        <tr>
          <th>生年月日</th>
          <td><%= @patient.birthday.strftime("%Y年%m月%d日") %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @patient.tel %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @patient.mail %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td>
            〒<%= @patient.postcode %><br>
            <%= @patient.address %>
          </td>
        </tr>
        <tr>
          <th>病気</th>
          <td><%= @patient.disease %></td>
        </tr>
      </tbody>
    </table>
    <%= link_to hospital_patients_path(@hospital), class: "btn btn-default" do %>
      <i class="fa fa-chevron-left fa-fw" aria-hidden="true"></i>一覧に戻る
    <% end %>
    <% unless @patient.family.present? %>
        <%= link_to "家族情報を追加", new_hospital_patient_family_path(@hospital, @patient), class: "btn btn-default" %>
    <% else %>
      <%= link_to "家族情報", hospital_patient_family_path(@hospital, @patient, @patient.family), class: "btn btn-info" %>
    <% end %>
    <%= link_to "編集", edit_hospital_patient_path(@hospital, @patient), class: "btn btn-default" %>
  </div>
  <div class="col-md-10 col-md-offset-1">
    <div class="row">
      <div class="col-md-4">
        <p class="title-bar patient__history">
          <span>診察履歴</span>
        </p>
        <table class="table table-striped table-bordered">
          <tbody>
            <tr>
              <th>2017年3月1日</th>
              <td><button type="button" class="btn btn-success btn-xs"><i class="fa fa-file-o fa-fw" aria-hidden="true"></i>CSV</button></td>
            </tr>
            <tr>
              <th>2017年3月1日</th>
              <td><button type="button" class="btn btn-success btn-xs"><i class="fa fa-file-o fa-fw" aria-hidden="true"></i>CSV</button></td>
            </tr>
            <tr>
              <th>2017年3月1日</th>
              <td><button type="button" class="btn btn-success btn-xs"><i class="fa fa-file-o fa-fw" aria-hidden="true"></i>CSV</button></td>
            </tr>
            <tr>
              <th>2017年3月1日</th>
              <td><button type="button" class="btn btn-success btn-xs"><i class="fa fa-file-o fa-fw" aria-hidden="true"></i>CSV</button></td>
            </tr>
            <tr>
              <th>2017年3月1日</th>
              <td><button type="button" class="btn btn-success btn-xs"><i class="fa fa-file-o fa-fw" aria-hidden="true"></i>CSV</button></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-md-8">
        <p class="title-bar patient__history">
          <span>カルテ情報</span>
        </p>
        <button type="button" class="btn btn-default">カルテ情報を編集する</button>
        <div class="patient__carte">
          <%= image_tag("img01.jpg", style: "width: 100%") %>
        </div>
      </div>
    </div>
  </div>
</div>